"""create_initial_tables

Revision ID: 5b33221a801c
Revises: 
Create Date: 2026-03-11 11:05:45.227181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <--- 添加这一行
import geoalchemy2  # <--- 添加这一行
# revision identifiers, used by Alembic.
revision: str = '5b33221a801c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dict_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dictionary_dict_code'), 'dictionary', ['dict_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dictionary_dict_code'), table_name='dictionary')
    op.drop_table('dictionary')
    # ### end Alembic commands ###
