"""create_initial_tables

Revision ID: a89f53681488
Revises: f045265ef45b
Create Date: 2026-03-11 12:29:27.108297

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = 'a89f53681488'
down_revision: Union[str, Sequence[str], None] = 'f045265ef45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
  #  op.create_index('idx_inspection_site_area', 'inspection_site', ['area'], unique=False, postgresql_using='gist')
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_street_name'), 'street', ['name'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('login_retry_count', sa.Integer(), nullable=False),
    sa.Column('openid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_openid'), 'user', ['openid'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('street_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['street_id'], ['street.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_name'), 'community', ['name'], unique=False)
    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('management_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('floor_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warranty_period', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area_size', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('inspection_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipment_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('equipment_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('venue_count', sa.Integer(), nullable=False),
    sa.Column('equipment_count', sa.Integer(), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=False),
    sa.Column('photo1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('community_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['community.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photo_url4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('inspection_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_inspection_current_location', 'inspection', ['current_location'], unique=False, postgresql_using='gist')
    op.create_table('maintenance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inspection_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('maintainer_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('issue_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maintenance_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_taken', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thumb_photo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_photo1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_photo2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_photo3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('completion_photo4', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=False),
    sa.Column('reported_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspection.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    #op.drop_table('spatial_ref_sys')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   # op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    
    op.drop_table('maintenance')
   # op.drop_index('idx_inspection_current_location', table_name='inspection', postgresql_using='gist')
    op.drop_table('inspection')
    op.drop_table('venue')
    op.drop_index(op.f('ix_community_name'), table_name='community')
    op.drop_table('community')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_openid'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_street_name'), table_name='street')
    op.drop_table('street')
   # op.drop_index('idx_inspection_site_area', table_name='inspection_site', postgresql_using='gist')
    op.drop_table('inspection_site')
    # ### end Alembic commands ###
