"""add_inspection_site_table

Revision ID: f045265ef45b
Revises: 5b33221a801c
Create Date: 2026-03-11 11:14:34.108997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # <--- 添加这一行
import geoalchemy2  # <--- 添加这一行

# revision identifiers, used by Alembic.
revision: str = 'f045265ef45b'
down_revision: Union[str, Sequence[str], None] = '5b33221a801c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inspection_site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('area', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_inspection_site_area', 'inspection_site', ['area'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('idx_inspection_site_area', table_name='inspection_site', postgresql_using='gist')
    op.drop_table('inspection_site')
    # ### end Alembic commands ###
